GAA-UAM/scikit-fda

- docs/modules/datasets.rst
- fda/datasets/__init__.py
- fda/datasets/_samples_generators.py
Added maker of a sinusoidal process, used in a example of registration.
> Sinusoidal dataset

- examples/plot_shift_registration_basis.py
Added first example of the registration module.
> Example of shift registration

- README.rst
- fda/basis.py
Fix Springer name on some docs
> Fixed publisher name

- fda/basis.py
Function that checks if two basis are defined on the same domain_range
> Basis domain check

- fda/basis.py
Fixed some properties checks from properties that doesn't exists
> Fixed basis properties that not exists

- examples/plot_boxplot.py
- fda/functional_data.py
Plotting the samples contained in the FDataGrid or FDataBasis by groups functionality added. 
Now, the color of each sample can be specified.
> enable plotting groups

- fda/functional_data.py
> Added @property decorator to ndim_codomain

- examples/plot_surface_boxplot.py
- fda/magnitude_shape_plot.py
- tests/test_magnitude_shape.py
> random_state

- pyproject.toml
Solves #83 more elegantly than #85.
> Add build requirements in pyproject.toml following PEP 518

- docs/modules/datasets.rst
- skfda/datasets/__init__.py
- skfda/datasets/_samples_generators.py
Pull request with the changes of #75, updated with the new name.
>New dataset generator, to make random warpings. The shape and smoothness of the warpings could be changed to make  differents families of functions.
> Random warping generator

- skfda/ml/clustering/base_kmeans.py
- skfda/representation/_functional_data.py
- skfda/representation/basis.py
- skfda/representation/grid.py
Allow integrating functional data objects as individual columns inside a Pandas DataFrame.
> Pandas integration

- docs/apilist.rst
- docs/conf.py
- docs/index.rst
- docs/modules/preprocessing.rst
- docs/modules/preprocessing/smoothing.rst
- examples/plot_kernel_smoothing.py
- skfda/_utils.py
- skfda/preprocessing/smoothing/kernel_smoothers.py
- skfda/preprocessing/smoothing/validation.py
- tests/test_smoothing.py
* Change the smoothing methods so that they have the scikit-learn API an can be used in a pipeline.
> Smoothing refactor

- skfda/representation/_functional_data.py
- skfda/representation/grid.py
- skfda/representation/interpolation.py
- tests/test_grid.py
- tests/test_pandas.py
Add tests for Pandas integration.
Fixed take method.
Should fix #133.
> Better Pandas integration of functional data

- docs/conf.py
- examples/plot_interpolation.py
- skfda/datasets/_samples_generators.py
- skfda/exploratory/visualization/magnitude_shape_plot.py
> Fix pdf compilation bugs

- examples/plot_representation.py
- skfda/preprocessing/registration/_landmark_registration.py
- skfda/representation/basis.py
- skfda/representation/grid.py
- tests/test_pandas.py
> Use `domain_range` of the data in  `to_basis` if not specified in the basis creation

- skfda/datasets/_real_datasets.py
Cherry-picked fix for the tests.
> Fix skdatasets new layout.

- examples/plot_extrapolation.py
- examples/plot_neighbors_functional_regression.py
- examples/plot_representation.py
- examples/plot_shift_registration_basis.py
- skfda/_utils/constants.py
- skfda/ml/regression/linear_model.py
- skfda/preprocessing/registration/_landmark_registration.py
- skfda/preprocessing/registration/_registration_utils.py
- skfda/preprocessing/registration/_shift_registration.py
- skfda/preprocessing/smoothing/_basis.py
- skfda/representation/basis.py
- skfda/representation/grid.py
- tests/test_basis.py
- tests/test_basis_evaluation.py
- tests/test_extrapolation.py
- tests/test_lfd.py
- tests/test_metrics.py
- tests/test_neighbors.py
- tests/test_pandas.py
- tests/test_regression.py
- tests/test_smoothing.py
The name was changed to keep a uniform nomenclature.
> Rename nbasis to n_basis.

- skfda/_neighbors/base.py
- skfda/_neighbors/classification.py
- skfda/_neighbors/outlier.py
- skfda/_neighbors/regression.py
- skfda/_neighbors/unsupervised.py
- skfda/preprocessing/registration/elastic.py
Now the doctests work in versions where
https://github.com/scikit-learn/scikit-learn/pull/17205 is merged.
> Fix doctests in new scikit-learn versions.

- skfda/preprocessing/dim_reduction/projection/_fpca.py
- tests/test_fpca.py
> fpca transform method quick fix

- docs/modules/ml/regression.rst
- skfda/ml/regression/__init__.py
- skfda/ml/regression/linear.py
- tests/test_regression.py
- tests/test_regularization.py
In the future is expected that this class can perform both scalar and
functional response prediction, depending on the target of the training
data.
> Rename `MultivariateLinearRegression` to `LinearRegression`.

- examples/plot_fpca.py
- skfda/preprocessing/dim_reduction/projection/_fpca.py
FPCA now stores the mean in fit, instead of modifying the input.
> Fix fpca modifies x

- docs/modules/misc/metrics.rst
- skfda/_neighbors/base.py
- skfda/_utils/__init__.py
- skfda/_utils/_utils.py
- skfda/misc/__init__.py
- skfda/misc/_math.py
- skfda/misc/metrics.py
- skfda/misc/operators/_identity.py
- skfda/misc/operators/_integral_transform.py
- skfda/misc/operators/_linear_differential_operator.py
- skfda/misc/operators/_operators.py
- skfda/misc/regularization/_regularization.py
- skfda/ml/regression/_coefficients.py
- skfda/ml/regression/linear.py
- skfda/preprocessing/dim_reduction/projection/_fpca.py
- skfda/representation/basis/_basis.py
- skfda/representation/basis/_fdatabasis.py
- skfda/representation/basis/_tensor_basis.py
- skfda/representation/basis/_vector_basis.py
- tests/test_basis.py
- tests/test_math.py
- tests/test_metrics.py
- tests/test_regression.py
Inner product refactored into a function.
All code for inner products is now using this implementation, including the computation of Gram matrices and Tikhonov regularization.
> Refactor inner product.

- tests/test_hotelling.py
- tests/test_oneway_anova.py
> Fixes the seed of ANOVA and Hotelling tests.

- skfda/misc/operators/_linear_differential_operator.py
- skfda/representation/basis/_fdatabasis.py
- tests/test_linear_differential_operator.py
> Remove `FDataBasis` method `to_list` as it is redundant.

- .travis.yml
- skfda/_utils/_utils.py
- skfda/ml/regression/linear.py
- skfda/representation/_functional_data.py
- skfda/representation/basis/_fdatabasis.py
- skfda/representation/grid.py
- skfda/representation/interpolation.py
- tests/test_pandas.py
- tests/test_pandas_fdatabasis.py
- tests/test_pandas_fdatagrid.py
Add some of the ExtensionArray standard tests for FDataGrid and FDataBasis, and fix the errors that appear.
> Improve pandas integration

- skfda/inference/anova/anova_oneway.py
- skfda/representation/basis/_basis.py
- skfda/representation/basis/_bspline.py
- skfda/representation/basis/_constant.py
- skfda/representation/basis/_fdatabasis.py
- skfda/representation/basis/_fourier.py
- skfda/representation/basis/_monomial.py
- skfda/representation/basis/_tensor_basis.py
- skfda/representation/basis/_vector_basis.py
- tests/test_basis.py
Multiplication is impossible for basis expansion in the general case, so
do not try to approximate it. Also currently there is no reason to do
so.
> Remove `times` function from `FDataBasis`.

- README.rst
- docs/modules/preprocessing/registration.rst
- examples/plot_elastic_registration.py
- skfda/preprocessing/registration/elastic.py
The DP method is more accurate than DP2. Also added a reference which was the first journal paper on these methods after the arxiv paper
> update references and change default method

- skfda/datasets/_real_datasets.py
The `as_frame` parameter returns data inside a pandas DataFrame object.
The returned dicts have also be changed to `Bunch` objects.
> Add `as_frame` parameter to available datasets

- examples/plot_kernel_smoothing.py
- setup.cfg
- setup.py
- skfda/datasets/_real_datasets.py
- skfda/exploratory/stats/_stats.py
Fix typing and style for real datasets.
> Datasets typing and style

- skfda/datasets/_real_datasets.py
The domain range is now (0, 365).
The grid points are now in the middle of the day interval.
> Fix the domain of the aemet dataset.

- setup.cfg
- skfda/preprocessing/registration/_shift_registration.py
- skfda/representation/basis/_tensor_basis.py
- skfda/representation/grid.py
- tests/test_basis.py
Fixes the Gram matrix for the Tensor basis.
> Fix tensor basis gram matrix

- setup.cfg
- skfda/_utils/_utils.py
- skfda/misc/_math.py
- skfda/representation/basis/_fdatabasis.py
- skfda/representation/grid.py
- tests/test_fdatagrid_numpy.py
Add typing to math functions.
Fix style of the math module.
Fix np.round with FDataGrid class.
Add a test fixture to test several monary ufuncs with FDataGrid argument.
> Typing math module

- docs/modules/misc/metrics.rst
- examples/plot_radius_neighbors_classification.py
- skfda/_utils/__init__.py
- skfda/_utils/_utils.py
- skfda/exploratory/outliers/neighbors_outlier.py
- skfda/exploratory/stats/_stats.py
- skfda/misc/metrics.py
- skfda/misc/operators/_identity.py
- skfda/ml/_neighbors_base.py
- skfda/ml/classification/_centroid_classifiers.py
- skfda/ml/classification/_neighbors_classifiers.py
- skfda/ml/clustering/_kmeans.py
- skfda/ml/clustering/_neighbors_clustering.py
- skfda/ml/regression/_neighbors_regression.py
- skfda/preprocessing/registration/validation.py
- skfda/representation/_typing.py
- tests/test_elastic.py
- tests/test_math.py
- tests/test_metrics.py
- tests/test_neighbors.py
Add typing to metrics.
Refactor the module to use classes instead of closures.
Refactor pairwise metric to not use all available memory.
Optimize pairwise L2 distance.
Improve the metrics in docs.
> Metric refactoring

- docs/modules/ml/clustering.rst
- docs/modules/ml/regression.rst
- docs/modules/representation.rst
- setup.cfg
- skfda/_utils/_utils.py
- skfda/ml/regression/__init__.py
- skfda/ml/regression/_historical_linear_model.py
Add the historical linear model from Malfait & Ramsay.
> Historical linear model

- skfda/representation/_functional_data.py
- skfda/representation/basis/_fdatabasis.py
- skfda/representation/grid.py
- tests/test_pandas.py
- tests/test_ufunc_numpy.py
Make operations between FData and ndarray commutative.
Also improve `take` implementation.
Closes #256.
> Makes operations between FData and ndarray commutative.

- skfda/preprocessing/registration/_landmark_registration.py
- tests/test_registration.py
Uniformize landmark locations.
Closes #404.
> Uniformize landmark locations.

- skfda/exploratory/visualization/_magnitude_shape_plot.py
> Add ellipsoid to the MS plot.

- skfda/representation/_functional_data.py
- skfda/representation/basis/_fdatabasis.py
- skfda/representation/grid.py
Closes #356: Implement unary minus for FData
> Implement unary minus for FData 

- skfda/preprocessing/smoothing/__init__.py
- skfda/preprocessing/smoothing/_kernel_smoothers.py
- skfda/preprocessing/smoothing/kernel_smoothers.py
Added removed kernel smoothing classes and module with deprecation warnings, to ease the transition from older versions.
> Add deprecated classes and modules for Kernel Smoothing.

- .gitignore
Changed the gitignore so that all files in the .vscode folder are ignored, instead of only ignoring the settings file
> Ignore the entire .vscode folder

- examples/plot_k_neighbors_classification.py
Several improvements to the example:
-  Fixing the problem outlined in #366 
-  Making the cross validation training simpler
-  Several spelling fixes and wording improvements
> Improve k_neighbors example

- skfda/misc/metrics/_fisher_rao.py
- skfda/misc/operators/_srvf.py
- skfda/preprocessing/registration/_fisher_rao.py
- skfda/preprocessing/registration/validation.py
See #530.
*Sorry for the delay*
> SRSF formula doc fix

- examples/full_examples/plot_aemet_unsupervised.py
- pyproject.toml
> Change example from Basemap to Cartopy.

- docs/modules/datasets.rst
- skfda/datasets/__init__.py
- skfda/datasets/_samples_generators.py
- skfda/tests/test_euler_maruyama.py
Included a function that makes numerical integration of an Îto SDE using the euler_maruyama shceme. It has been included in the datasets module to extend the functionality dedicated to generate synthetic data.
> Euler_maruyama function

- skfda/preprocessing/feature_construction/_function_transformers.py
Small formatting correction in LocalAveragesTransformer, OccupationMeasureTransformer and NumberCrossingsTransformer so that examples can be properly visualized.
> Formatting Correction in Feature Construction
