GAA-UAM/scikit-fda

- fda/FDataGrid.py
- fda/validation.py
- Corrected creation of multidimensional `FDataGrid` objects with
different number of sample points in each dimension. As a result,
`sample_points` is now a list of arrays. The doctests have been changed
accordingly.
- Corrected multidimensional mean (using `keepdims`).
- Improved `__getitem__` to allow not to specify values for some
dimensions. The problem with keys that are not slices remains.
- Added checks in plot an scatter of the dimension of the image.
- Changed round to not rounding sample points by default (maybe with an
additional argument?).
> Several corrections related with multidimensional `FDataGrid` objects.

- fda/grid.py
The purpose of this PR is to add support for numpy ufuncs in FDataGrid objects. With this PR, code such as:
```
import fda
a = fda.datasets.make_gaussian_process()
b = np.sin(a)
```
is valid, and some functions in the math module can be removed (but this PR does not remove them right now).
I would want to discuss several topics related with the current and future implementations:
- FDataGrid matrix mutability. As discussed before, matrix mutability is a problem, as it requires us to detect changes and change the interpolation object, for example. Some ufuncs modify the input arrays, and also FDatagrid objects can be passed as `out` parameters. We should think about the best way to deal with that.
- Operations as ufuncs. Maybe it is useful to change operations such as sum and …
> First version supporting ufuncs in FDataGrid

- tests/test_basis.py
- tests/test_basis_evaluation.py
- tests/test_grid_spline_interpolation.py
Depending on the numpy version, there may be slight changes in the results that can cause the tests to fail by using `round` and `array_equal` which can be avoided using `array_almost_equal`. See #78.
Changes:
* `array_equal` -> `array_almost_equal`
* Changes in code indentation to follow PEP8
> Test changes to avoid failure with other numpy versions

- docs/Makefile
- docs/_templates/autosummary/base.rst
- docs/_templates/autosummary/class.rst
- docs/conf.py
Adds a link to related examples in the documentation of classes and functions. Note that some examples use wild imports, and should be changed for this to catch the imported objects.
> Add backreferences to examples

- README.rst
- setup.py
> Pypi description

- skfda/misc/metrics.py
Noticed a small error in the docs
> Correct 'amplitude' -> 'phase' in phase_distance function documentation

- examples/plot_landmark_shift.py
- examples/plot_representation.py
- skfda/_neighbors/base.py
- skfda/datasets/_real_datasets.py
- skfda/datasets/_samples_generators.py
- skfda/exploratory/depth/_depth.py
- skfda/exploratory/depth/multivariate.py
- skfda/exploratory/outliers/_directional_outlyingness.py
- skfda/exploratory/visualization/_boxplot.py
- skfda/exploratory/visualization/_magnitude_shape_plot.py
- skfda/exploratory/visualization/clustering_plots.py
- skfda/misc/_math.py
- skfda/misc/metrics.py
- skfda/ml/clustering/base_kmeans.py
- skfda/preprocessing/registration/_elastic.py
- skfda/preprocessing/registration/_landmark_registration.py
- skfda/preprocessing/registration/_registration_utils.py
- skfda/preprocessing/registration/_shift_registration.py
- skfda/preprocessing/smoothing/_linear.py
- skfda/representation/_functional_data.py
- skfda/representation/basis.py
- skfda/representation/evaluator.py
- skfda/representation/extrapolation.py
- skfda/representation/grid.py
- skfda/representation/interpolation.py
- tests/test_grid.py
- tests/test_metrics.py
- tests/test_neighbors.py
* `ndim_domain` is now `dim_domain`
* `ndim_codomain` is now `dim_codomain`
* `ndim_image` is removed, as it was redundant with `ndim_codomain` and
the dimension is a property of the codomain and not the image.
The old names where based in numpy nomenclature, which is
matrix-centric. The new names try to reflect the usual conventions for
functions.
> Renamed attributes related with dimensions of functions:

- skfda/exploratory/outliers/_directional_outlyingness.py
- skfda/ml/clustering/base_kmeans.py
- skfda/representation/grid.py
An FDatagrid shape is now `(n_samples,)` (inherited from Panda's
`ExtensionArray`) as a FDataGrid is an array of functions with the same
evaluation points.
Closes #141.
> Remove the custom definition of shape for FDataGrid.

- examples/plot_boxplot.py
- examples/plot_clustering.py
- examples/plot_explore.py
- examples/plot_k_neighbors_classification.py
- examples/plot_magnitude_shape.py
- examples/plot_magnitude_shape_synthetic.py
- examples/plot_radius_neighbors_classification.py
- examples/plot_representation.py
- skfda/exploratory/visualization/representation.py
- skfda/representation/_functional_data.py
* Rename sample_labels to group.
* Rename label_colors to group_colors.
* Rename label_names to group_names.
* `group` is now not required to be an array of integers, closes #165.
* `group_colors` and `group_names` are now objects that index the
color/name per group (so if `group` is an array of integers, they can
still be arrays, but they can be dict-like objects for other types).
* A new parameter `legend` allows to plot a legend even if no
`group_names` is passed (it will use the objects passed to `group`).
* The *explore* example is changed to make use of some of these features
in order to test them.
> Changes to plotting groups

- setup.py
Currently we relied in some features of Numpy 1.16 but we did not specify that. We should specify the version in order for the installation tools to update the version appropriately.
> Set required numpy version.

- docs/modules/preprocessing/dim_reduction/fpca.rst
- examples/plot_fpca.py
- skfda/preprocessing/dim_reduction/projection/__init__.py
- skfda/preprocessing/dim_reduction/projection/_fpca.py
- tests/test_fpca.py
Unify both modules as most functionalities are the same.
Now it does not matter if FDataBasis or FDataGrid is passed.
This change is further justified because of the unification of penalization for both FDataBasis and FDataGrid objects.
> unify FPCAGrid and FPCABasis

- skfda/datasets/_real_datasets.py
The phonemes dataset contains 256 points equally spaced from 0-8 kHz. Before this, we are considering that the domain range is 0-255 which is incorrect and does not have a scale.
> Change phonemes dataset domain range to 0-8kHz

- examples/plot_explore.py
- examples/plot_interpolation.py
- skfda/exploratory/visualization/representation.py
- skfda/misc/metrics.py
- skfda/misc/operators/_linear_differential_operator.py
- skfda/preprocessing/registration/_shift_registration.py
- skfda/preprocessing/registration/validation.py
- skfda/representation/_evaluation_trasformer.py
- skfda/representation/_functional_data.py
- skfda/representation/basis/_basis.py
- skfda/representation/basis/_bspline.py
- skfda/representation/basis/_constant.py
- skfda/representation/basis/_fdatabasis.py
- skfda/representation/basis/_fourier.py
- skfda/representation/basis/_monomial.py
- skfda/representation/evaluator.py
- skfda/representation/extrapolation.py
- skfda/representation/grid.py
- skfda/representation/interpolation.py
- tests/test_basis_evaluation.py
- tests/test_fpca.py
- tests/test_interpolation.py
- tests/test_registration.py
Derivatives are now separated from evaluation and plotting.
- Now a full object representing the derivative must be constructed and evaluated using `derivative()`.
- Fixed construction of `derivative` for some basis.
- `derivative` now works for higher dimensional `FDataGrid` objects. Order must be a tuple with the order of each partial derivative involved.
> Rework differentiation

- skfda/_utils/__init__.py
- skfda/_utils/_utils.py
- skfda/preprocessing/registration/_shift_registration.py
- skfda/representation/_functional_data.py
- skfda/representation/basis/_fdatabasis.py
- skfda/representation/evaluator.py
- skfda/representation/extrapolation.py
- skfda/representation/grid.py
- skfda/representation/interpolation.py
- tests/test_basis_evaluation.py
- tests/test_grid.py
- tests/test_interpolation.py
- tests/test_registration.py
- Simplify internal code
- Only one entry point for evaluation in evaluators and `FData` objects
- Rename `aligned_evaluation` to `aligned`
- Allow ragged input for unaligned evaluation
> Simplify evaluation

- docs/modules/representation.rst
- skfda/_utils/__init__.py
- skfda/_utils/_utils.py
- skfda/misc/operators/_operators.py
- skfda/preprocessing/smoothing/_basis.py
- skfda/representation/_functional_data.py
- skfda/representation/basis/__init__.py
- skfda/representation/basis/_basis.py
- skfda/representation/basis/_bspline.py
- skfda/representation/basis/_fdatabasis.py
- skfda/representation/basis/_fourier.py
- skfda/representation/basis/_monomial.py
- skfda/representation/basis/_vector_basis.py
- skfda/representation/grid.py
- tests/test_basis.py
- tests/test_basis_evaluation.py
- tests/test_regularization.py
- tests/test_smoothing.py
- The `VectorValued` basis construct a basis for vector valued functions from several scalar valued basis (one per axis).
- Can be derived, and converted from a `FDataGrid`.
- Regularization takes codomain dimension into account.
> Add basis for functions with codomain dimension above 1

- skfda/representation/grid.py
- tests/test_grid.py
`FDataGrid` (as `FDataBasis`) should behave as an array of functions, so there should not be indexed using tuples. Closes #57.
> Remove indexing in FDataGrid additional dimensions.

- examples/plot_kernel_smoothing.py
The example used the Phoneme dataset, whose discretization points where relabeled in #226 to match the original data.
The smoothing parameter of NadarayaWatson and LocalLinearRegression smoothers depends on the values of those points, so its values had to be changed.
> Fix kernel smoothing example.

- skfda/_utils/_utils.py
- skfda/preprocessing/registration/base.py
- skfda/preprocessing/registration/validation.py
- tests/test_elastic.py
- tests/test_registration.py
- Added typing and refactor code according to our style guide.
- All but one scorer do not longer require the discretization of functions, relying instead on the L2 distance.
- Fixed some errors where the L2 distance was not properly squared to match the formula.
@pablomm I know you are not longer as involved with the project as before, but as you are the original author of this module I appreciate any suggestions that you can make.
> Refactor registration scorers

- examples/plot_elastic_registration.py
- examples/plot_explore.py
- skfda/representation/basis/_fdatabasis.py
- skfda/representation/grid.py
Fix #324.
Remove the change of dataset_name for FDataGrid derivative, and fix the
examples that relied in the old behaviour.
> Preserve attributes in FDataBasis derivative, and do not change dataset_name

- examples/plot_fpca_inverse_transform_outl_detection.py
I propose an example of using ``inverse_transform`` in ``FPCA`` to detect outliers from the reconstruction error (RE) between the input and the _recovered_ input from the eigenspace.
In other words, given a fitted fpca, a threshold and a test sample ``x`` the decision rule is:
```javascript
x_hat  = fpca.inverse_transform(fpca.transform(x))
RE = lp_distance(x, x_hat, p=2) / lp_norm(x, p=2)
if RE>= threshold:
print('x is an outlier')
```
In the example, we use synthetic data generated from centered gaussian processes. The nonoutliers are generated with a Gaussian kernel and the outliers are generated with an exponential kernel. There are only nontouliers in the training dataset (used to fit the FPCA and set the threshold). There are both outliers and nonoutliers in the test samples.
I …
> Example fpca.inverse_transform to detect outliers

- skfda/exploratory/outliers/_directional_outlyingness.py
- skfda/exploratory/visualization/_magnitude_shape_plot.py
- This alpha parameter was only used in the asymptotic case, when the
number of samples was too high.
- Add instead a cutoff_factor parameter that multiplies the cutoff and
can be used for an arbitrary number of samples, to consider more or less
functions as outliers.
> Remove alpha parameter of Magnitude-Shape plot and outlier detector.

- examples/plot_kernel_regression.py
- skfda/misc/hat_matrix.py
- skfda/ml/regression/_kernel_regression.py
- tests/test_kernel_regression.py
> LLR for non orthonormal basis

- examples/plot_composition.py
- examples/plot_interpolation.py
- skfda/exploratory/stats/_functional_transformers.py
- skfda/preprocessing/feature_construction/_function_transformers.py
- skfda/representation/interpolation.py
- skfda/tests/test_interpolation.py
- Vectorizes interpolation of FDataGrid using the "new" SciPy API.
- Removes spline smoothing functionality from interpolators, as it was not true interpolation and was not vectorizable.
- Due to some Scipy limitations not all interpolation orders are available in oldest SciPy versions for every domain dimension. As interpolation is rarely changed, though, and most algorithms do not interpolate, we will break backwards compatibility here to achieve vectorization.
- In the rare cases where a user needs the old behaviour, they can always create their own interpolation class from the old code.
> Speed up evaluation of FDataGrid

- skfda/preprocessing/dim_reduction/_fpca.py
The underscore at the end of the variable name was lost in refactoring in a previous commit.
> Fix wrong variable name in fpca

- skfda/preprocessing/dim_reduction/_fpca.py
- skfda/tests/test_fpca.py
Choosing the weights for the numerical quadrature used during the calculation of FPCA does not seem like a parameter that the end user should need to tweak. Therefore, it has been removed from the documentation, and its name in the constructor has been prepended with an underscore to indicate that it is a private parameter now
> Make weights parameter private

- skfda/tests/test_fpca.py
After diving through the source of fda.usc, I noticed that the int.simpson2 function uses trapezoid weights for the integration. 
If we use those weights to calculate the scores, the results match perfectly.
> Change quadrature in fpca test

- skfda/misc/metrics/_mahalanobis.py
- skfda/preprocessing/dim_reduction/_fpca.py
The constructor for `FPCA` receives parameters in a different order than the one used in `Mahalanobis`.
https://github.com/GAA-UAM/scikit-fda/blob/05a35df781d65918d8730195f61a93a72198f2e1/skfda/preprocessing/dim_reduction/_fpca.py#L87-L94
Thus, the last two parameters should be interchanged in the call to the constructor in `Mahalanobis`.
> Hotfix: Correct the order of the parameters for the FPCA in Mahalanobis

- skfda/preprocessing/dim_reduction/_fpca.py
- skfda/tests/test_fpca.py
As outlined in #507, when the number of components is not specified, all components should be extracted. A deprecation warning has been added to alert the users that were relying on the default value of components being 3. The documentation has also been updated accordingly.
> Deprecate 3 as the default number of components in FPCA

- docs/modules/representation.rst
- skfda/representation/basis/_custom_basis.py
The CustomBasis documentation was added to `representation.rst`. Additionally, a left-over doc string and an incorrect whitespace were removed.
> Make CustomBasis documentation accesible

- skfda/representation/_functional_data.py
As the documention specifies, axis can be either None or 0.
Currently, if 0 is given as the axis, a mypy error is raised since the function signature only accepts a None axis.
> Change type of axis in FData's mean method to accept zero.

- .github/workflows/mypy.yml
Currently, the `mypy` action does not find all errors and reports some false positives. 
For example, it consistently outputs:
```
Untyped decorator makes function "test_simple_regresion_dataset_functional" untyped [misc]
```
This is because the current action does not install the required Python packages for `mypy` to have all the typing information it needs. 
Additionally, I think the action should fail when there are `mypy` errors. The current configuration still marks it as a success in the pull request test summary. 
I tested these changes in the PLS pull request, and they work.
> Update mypy workflow

- skfda/preprocessing/smoothing/validation.py
Add missing parameter to constructor so that tests pass with scikit-learn 1.3.0 (new version released today :) )
> Fix tests for scikit learn 1.3.0

- examples/plot_fpca_regression.py
Several issues have been addressed:
- Fix the labels of the cross validation plot
- Change cross validation plot style
- Round scores to four decimal places
> Polish fpca regression example

- docs/refs.bib
- skfda/ml/classification/_centroid_classifiers.py
The image shows the locally generated doc after the changes.
Closes #535
> Update citation and See also in DTMClassifier class

- skfda/exploratory/stats/_stats.py
- skfda/misc/covariances.py
- skfda/misc/scoring.py
- skfda/ml/clustering/_kmeans.py
- skfda/representation/_functional_data.py
- skfda/representation/basis/_fdatabasis.py
- skfda/representation/grid.py
Change `ddof` argument name to `correction` to match the Python array API standard.
Closes #576
> Change `ddof` argument to `correction` in var and cov functions

- skfda/representation/basis/_bspline_basis.py
Fix message and condition (n_basis < order) in the initialization of a BSplineBasis.
Current condition is equivalent to previous one. The message has been corrected to match the condition.
Closes #575
> BSplineBasis initialization incorrect error message

- .github/workflows/tests.yml
- pyproject.toml
- readthedocs.yml
- skfda/_utils/_neighbors_base.py
- skfda/datasets/_real_datasets.py
- skfda/datasets/_samples_generators.py
- skfda/exploratory/depth/_depth.py
- skfda/exploratory/outliers/_directional_outlyingness.py
- skfda/exploratory/stats/_fisher_rao.py
- skfda/exploratory/visualization/_magnitude_shape_plot.py
- skfda/inference/anova/_anova_oneway.py
- skfda/misc/operators/_linear_differential_operator.py
- skfda/misc/operators/_srvf.py
- skfda/ml/clustering/_neighbors_clustering.py
- skfda/ml/regression/_historical_linear_model.py
- skfda/preprocessing/dim_reduction/_fpca.py
- skfda/preprocessing/dim_reduction/_fpls.py
- skfda/preprocessing/feature_construction/_function_transformers.py
- skfda/preprocessing/feature_construction/_functions.py
- skfda/tests/test_clustering.py
- skfda/tests/test_elastic.py
- skfda/tests/test_fpca_regression.py
- skfda/tests/test_fpls_regression.py
- skfda/tests/test_metrics.py
- skfda/tests/test_neighbors.py
- skfda/tests/test_registration.py
- skfda/tests/test_regression.py
- Remove support for Python 3.9 according to [SPEC 0](https://scientific-python.org/specs/spec-0000/).
- Fix test discrepancies with newer Scipy versions.
SciPy version 1.11 changes how Simpson quadrature is computed with an even number of points (https://github.com/scipy/scipy/pull/18209).
This caused some test to fail, as the values of the integrals and metrics used change, causing in some cases several discrepancies (https://github.com/GAA-UAM/scikit-fda/issues/551).
This has been fixed to make the tests compatible with both previous versions and versions after 1.11, in two main ways:
- By making some comparisons more lenient, allowing for higher relative or absolute tolerances.
- By rewriting some tests in order to be less sensitive to changes in quadrature by design.
> Remove support for Python 3.9.

- skfda/representation/irregular.py
Integration for irregular curves has been implemented using `scipy.integrate.simpson` to integrate irregular curves (of 1-dimensional domain) one by one.
We have not agreed on how integration of irregular data with higher dimensional domains should be defined, so it is not to be implemented yet.
This is a first implementation which may or may not be later improved by manually computing simpson's coefficients, multiply them against the curves' values and calling `skfda.representation.irregular._reduceat` to add the results.
> Integrate `FDataIrregular` using `scipy.integrate.simpson` on each curve separately 

- skfda/representation/irregular.py
- skfda/tests/test_irregular.py
`FDataIrregular`'s `__getitem__` had incorrect computation of the `start_indices` of the new object.
This could perhaps be considered a hotfix.
Added test to check correction (previous version did not pass this test). The previous version was incorrect unless all samples in the new `FDataIrregular` object had the same number of measurements; this is why it has been hard to notice the mistake.
> Fix FDataIrregular's __getitem__

- skfda/__init__.py
- skfda/misc/scoring.py
- skfda/representation/irregular.py
- skfda/tests/test_scoring.py
This pull request depends on #608 (integrating `FDataIrregular` objects is needed to implement the scores).
As explained in #609 , `mean_absolute_error`, `mean_absolute_percentage_error`, `mean_squared_error` and `mean_squared_log_error` have been implemented in the case when both `y_true` and `y_pred` are `FDataIrregular` objects.
Test cases have been included to ensure the same score is obtained if the `FDataIrregular` objects are obtained from `FDataGrid`'s.
> Implement scores for `FDatairregular` objects as described in #609 

- skfda/preprocessing/dim_reduction/_fpca.py
`self._weights = scipy.integrate.simpson(y=identity, x=X.grid_points[0])`
should replace
`self._weights = scipy.integrate.simpson(identity, X.grid_points[0])`
in FPCA._fit_grid (currently line 351 in "Functional Principal Component Analysis Module.")
By not specifying x and y, simpson() returns the error:
`TypeError: simpson() takes 1 positional argument but 2 were given`
> Explicit arguments for simpson

- pyproject.toml
- skfda/_utils/_neighbors_base.py
- skfda/representation/irregular.py
Fixed the code that was failing in the tests for Scipy 1.14:
- Calls to simpson with more than one positional parameters are invalid (https://github.com/scipy/scipy/pull/20554).
- Representation of SciPy sparse matrix in doctests has changed (https://github.com/scipy/scipy/pull/20649).
- As this change makes tests fail for previous SciPy versions, the minimum version of SciPy used for tests has been set to 1.14.
> Support SciPy 1.14.

- pyproject.toml
- skfda/_utils/_utils.py
- skfda/exploratory/outliers/_directional_outlyingness.py
- skfda/misc/_math.py
- skfda/misc/covariances.py
- skfda/misc/operators/_linear_differential_operator.py
- skfda/ml/classification/_centroid_classifiers.py
- skfda/ml/classification/_depth_classifiers.py
- skfda/ml/classification/_neighbors_classifiers.py
- skfda/ml/classification/_qda.py
- skfda/ml/clustering/_hierarchical.py
- skfda/ml/regression/_historical_linear_model.py
- skfda/preprocessing/dim_reduction/variable_selection/recursive_maxima_hunting.py
- skfda/preprocessing/feature_construction/_function_transformers.py
- skfda/preprocessing/feature_construction/_functions.py
- skfda/preprocessing/feature_construction/_per_class_transformer.py
- skfda/preprocessing/registration/validation.py
- skfda/preprocessing/smoothing/validation.py
- skfda/representation/basis/_fdatabasis.py
- skfda/representation/grid.py
- skfda/representation/irregular.py
- skfda/tests/test_pandas_fdatabasis.py
- skfda/tests/test_pandas_fdatagrid.py
All tests are now executed with NumPy 2. This is important, because the representation of arrays (and thus the expected doctest output) has been changed in this version.
> Allow to use NumPy 2.

- examples/plot_clustering.py
No issue was reported regarding the error in the clustering example.
In the clustering example, a couple of the explanations of the code did not match the code itself. For instance you could read:
> To see the information in a graphic way, the method plot_clusters() can be used.
However, instead of using `plot_clusters()`, the following class was used:
>ClusterPlot(kmeans, fd, cluster_colors=cluster_colors, cluster_labels=cluster_labels).plot()
> Clustering example error fixed
